### ISSUE TITLE
When use with Webpack+React+Babel-loader get error: You gave us a visitor for the node type "TSDeclareFunction" but it's not a valid type

### ISSUE THREAD

**Issue by budarin** [microsoft/TypeScript-Babel-Starter#17]
I use to you description to migrate webpack+Babel+React app to typescript but get the error:
```
> Executing task: npm run start <


> minimal-react-webpack-babel-setup@1.0.0 start d:\Projects\react-bootstrap-project
> webpack-dev-server --mode development --config ./config/webpack.config.babel.js

babel-preset-env: `DEBUG` option

Using targets:
{
  "node": "10.5"
}

Modules transform: commonjs

Using plugins:
d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: You gave us a visitor for the node type "TSDeclareFunction" but it's not a valid type (While processing preset: "d:\\Projects\\react-bootstrap-project\\node_modules\\babel-preset-typescript\\lib\\index.js")
    at verify (d:\Projects\react-bootstrap-project\node_modules\babel-traverse\lib\visitors.js:196:13)
    at Function.explode (d:\Projects\react-bootstrap-project\node_modules\babel-traverse\lib\visitors.js:72:3)
    at Plugin.normaliseVisitor (d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\plugin.js:155:29)
    at new Plugin (d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\plugin.js:66:27)
    at Function.memoisePluginContainer (d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:119:21)
    at Function.normalisePlugin (d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:146:32)
    at d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (d:\Projects\react-bootstrap-project\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
```
Here is my [repository](https://github.com/budarin/react-bootstrap-project)

**Comment by budarin** [comment]
I've found [solution ](https://github.com/babel/babel/issues/6392)
